import type { TourStep } from "@/lib/tours/types";

export const ONBOARDING_TOUR_STEPS: TourStep[] = [
  {
    id: "nav-search",
    target: '[data-tour="nav-search"]',
    title: "Jump to any symbol",
    description: "Search a ticker to open its chart, patterns, catalysts, and options chain. Your last 5 searches are remembered here too.",
    side: "bottom",
  },
  {
    id: "dashboard-stats",
    path: "/",
    target: '[data-tour="dashboard-stats"]',
    title: "Your paper portfolio",
    description: "Cash balance, starting balance, and total P&L — a $100k paper account you can't actually lose money from.",
    side: "bottom",
  },
  {
    id: "dashboard-positions",
    target: '[data-tour="dashboard-positions"]',
    title: "Open positions at a glance",
    description: "Every open trade shows up here with live P&L, right on the Dashboard.",
    side: "top",
  },
  {
    id: "symbol-chart",
    path: "/symbol/SPY",
    target: '[data-tour="symbol-chart"]',
    title: "Candlestick chart",
    description: "Daily candles for whatever symbol you're looking at — the foundation for everything else on this screen.",
    side: "right",
  },
  {
    id: "symbol-patterns",
    target: '[data-tour="symbol-patterns"]',
    title: "Detected patterns, explained",
    description: "Candlestick patterns are found automatically and explained in plain language — hover one to see where it fired on the chart.",
    side: "left",
  },
  {
    id: "symbol-catalysts",
    target: '[data-tour="symbol-catalysts"]',
    title: "News and catalysts",
    description: "Recent headlines and upcoming earnings, plus an on-demand sentiment check — so your trade thesis is grounded in something real.",
    side: "top",
  },
  {
    id: "symbol-options",
    target: '[data-tour="symbol-options"]',
    title: "Options chain",
    description: "Real strikes, expirations, and bid/ask. Click a price to open the trade ticket and Decision Framework.",
    side: "top",
  },
  {
    id: "positions-table",
    path: "/positions",
    target: '[data-tour="positions-table"]',
    title: "All positions",
    description: "Every open, closed, and expired trade lives here, including days-to-expiration for anything still open.",
    side: "top",
  },
  {
    id: "journal-table",
    path: "/journal",
    target: '[data-tour="journal-table"]',
    title: "Trade journal",
    description: "Every trade's stated thesis, graded after it closes on direction, magnitude, timing, and IV read.",
    side: "top",
  },
  {
    id: "learn-accordion",
    path: "/learn",
    target: '[data-tour="learn-accordion"]',
    title: "Learn Hub",
    description: "A 9-lesson curriculum covering everything from candlesticks to IV crush — worth working through before you trade seriously.",
    side: "top",
  },
];
