"""initial schema

Revision ID: 0122f5ddcf76
Revises: 
Create Date: 2026-07-21 10:50:16.567369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0122f5ddcf76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='chat_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context_type', sa.Enum('lesson', 'trade', 'symbol', name='chat_context_type'), nullable=False),
    sa.Column('context_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('starting_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote_cache',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('ohlc_json', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('option_type', sa.Enum('call', 'put', 'none', name='option_type'), nullable=False),
    sa.Column('strike', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('expiration', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', 'expired', name='position_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('open', 'close', name='trade_action'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fill_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('tradier_order_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('catalyst', sa.Enum('earnings', 'news', 'technical_setup', 'momentum', 'macro_event', 'none', name='catalyst'), nullable=False),
    sa.Column('direction', sa.Enum('up', 'down', name='direction'), nullable=False),
    sa.Column('expected_magnitude', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('iv_at_entry', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('timeframe_rationale', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('grade_direction', sa.Boolean(), nullable=True),
    sa.Column('grade_magnitude', sa.Boolean(), nullable=True),
    sa.Column('grade_timing', sa.Boolean(), nullable=True),
    sa.Column('grade_iv_crush', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_entries')
    op.drop_table('trades')
    op.drop_table('positions')
    op.drop_table('quote_cache')
    op.drop_table('portfolios')
    op.drop_table('lessons')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
