"""add lesson quiz_json and scenario_json columns

Revision ID: 1db632346c68
Revises: aedddb4c97c3
Create Date: 2026-07-22 11:55:25.827781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1db632346c68'
down_revision: Union[str, Sequence[str], None] = 'aedddb4c97c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('quiz_json', sa.JSON(), nullable=True))
    op.add_column('lessons', sa.Column('scenario_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'scenario_json')
    op.drop_column('lessons', 'quiz_json')
    # ### end Alembic commands ###
