"""add news_cache and sentiment_cache tables

Revision ID: 2fb78348b2c7
Revises: b0650e681d86
Create Date: 2026-07-22 10:53:41.248166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fb78348b2c7'
down_revision: Union[str, Sequence[str], None] = 'b0650e681d86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_cache',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('news_json', sa.JSON(), nullable=False),
    sa.Column('earnings_json', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('sentiment_cache',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('sentiment_json', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentiment_cache')
    op.drop_table('news_cache')
    # ### end Alembic commands ###
