"""add journal entry underlying price columns

Revision ID: 562057f41bfb
Revises: 0122f5ddcf76
Create Date: 2026-07-21 13:07:16.559477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '562057f41bfb'
down_revision: Union[str, Sequence[str], None] = '0122f5ddcf76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('underlying_price_at_entry', sa.Numeric(precision=12, scale=4, asdecimal=False), nullable=False))
    op.add_column('journal_entries', sa.Column('underlying_price_at_exit', sa.Numeric(precision=12, scale=4, asdecimal=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_entries', 'underlying_price_at_exit')
    op.drop_column('journal_entries', 'underlying_price_at_entry')
    # ### end Alembic commands ###
