"""add lesson walkthrough_json column

Revision ID: aedddb4c97c3
Revises: 2fb78348b2c7
Create Date: 2026-07-22 11:40:02.936637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aedddb4c97c3'
down_revision: Union[str, Sequence[str], None] = '2fb78348b2c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('walkthrough_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'walkthrough_json')
    # ### end Alembic commands ###
